name: flutter_application_2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  http: ^1.6.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cucimotor.jpg
    - assets/images/promo.jpg
    - assets/images/detailing.jpg
    - assets/images/detailing engine.jpg
    - assets/images/detailing full.jpg
    - assets/images/profil.jpg
    - assets/images/splash.png
    - assets/images/promo1.jpg
    - assets/images/promo2.jpg
    - assets/images/promo3.jpg
    - assets/images/polish body.jpg
    - assets/images/polish helm.jpg
